updated format and yml file

diff --git a/.github/workflows/linting.yml b/.github/workflows/linting.yml
--- a/.github/workflows/linting.yml
+++ b/.github/workflows/linting.yml
@@ -27,6 +27,8 @@ jobs:
 
       - name: Fail?
         if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!" && exit 1
+        run: |
+          echo "Some files failed the linting checks!" 
+          exit 1
 
       
